//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTransfer
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<int> FromEmployeeId { get; set; }
        public Nullable<int> ToEmployeeId { get; set; }
        public string Note { get; set; }
        public Nullable<int> AssetID { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Asset Asset { get; set; }
    }
}
